apiVersion: v1
kind: Service
metadata:
  name: jobposting-service
spec:
  type: NodePort
  selector:
    app: jobposting
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007